[tool.poetry]
name = "pyren"
version = "3.0.alpha"
description = ""
authors = ["anatoliis <15053145+anatoliis@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
